--create database TOTAL_AMT_DW
USE TOTAL_AMT_DW
GO
select * from TOTAL_AMT_DW.dbo.TOTAL2
CREATE TABLE DEPARTMENT_DIM
( 
DEP_ID INT NOT NULL IDENTITY,
DEPT_CD VARCHAR(MAX) NOT NULL,
DEPT_NM VARCHAR(MAX) NOT NULL,
PRIMARY KEY (DEP_ID));
GO
CREATE TABLE FUND_DIM
( 
FUND_ID INT NOT NULL IDENTITY,
FUND_CD VARCHAR(1000) NOT NULL,
FUND_NM VARCHAR(1000) NOT NULL,
PRIMARY KEY (FUND_ID));
GO
CREATE TABLE PROGRAM_DIM
( 
DIV_ID INT NOT NULL IDENTITY,
DIV_CD VARCHAR(MAX) NOT NULL,
DIV_NM VARCHAR(MAX) NOT NULL,
PRIMARY KEY (DIV_ID));
GO
CREATE TABLE ACTIVITY_DIM
( 
GP_ID INT NOT NULL IDENTITY,
GP_CD VARCHAR(MAX) NOT NULL,
GP_NM VARCHAR(MAX) NOT NULL,
PRIMARY KEY (GP_ID));
GO
CREATE TABLE OBJECT_DIM
( 
OBJ_ID INT NOT NULL IDENTITY,
OBJ_CD VARCHAR(1000) NOT NULL,
OBJ_NM VARCHAR(1000) NOT NULL,
PRIMARY KEY (OBJ_ID));
GO
CREATE TABLE VEND_DIM
( 
VEND_ID INT NOT NULL IDENTITY,
LGL_NM VARCHAR(MAX) NOT NULL,
VEND_CUST_CD VARCHAR(MAX) NOT NULL,
PRIMARY KEY (VEND_ID));
GO
CREATE TABLE CALENDAR_DIM
( 
CAL_ID INT NOT NULL IDENTITY,
CAL_YEAR VARCHAR(1000) NOT NULL,
CAL_MONTH VARCHAR(1000) NOT NULL,
PRIMARY KEY (CAL_ID));
GO
CREATE TABLE REF_DOCUMENT_DIM
( 
RF_DOC_ID INT NOT NULL IDENTITY,
RF_DOC_CD VARCHAR(MAX) NOT NULL,
RFED_ACTG_LN_NO VARCHAR(MAX) NOT NULL,
ACTG_LN_DSCR VARCHAR(MAX) NOT NULL,
PRIMARY KEY (RF_DOC_ID));
GO
CREATE TABLE TOTAL_AMOUNT_FACT1
(
DEP_ID INT,
FUND_ID INT,
DIV_ID INT,
GP_ID INT,
OBJ_ID INT,
VEND_ID INT,
CAL_ID INT,
RF_DOC_ID INT,
AMOUNT_TOTAL VARCHAR(MAX) NOT NULL,
STS VARCHAR(MAX) NOT NULL,
STS_AMOUNT FLOAT DEFAULT 0,
PRIMARY KEY(DEP_ID,FUND_ID,DIV_ID,GP_ID,OBJ_ID,VEND_ID,CAL_ID,RF_DOC_ID),
FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT_DIM (DEP_ID),
FOREIGN KEY (FUND_ID) REFERENCES FUND_DIM(FUND_ID),
FOREIGN KEY (VEND_ID) REFERENCES VEND_DIM(VEND_ID),
FOREIGN KEY (CAL_ID) REFERENCES CALENDAR_DIM(CAL_ID),
FOREIGN KEY (RF_DOC_ID) REFERENCES REF_DOCUMENT_DIM(RF_DOC_ID)
);

