UPDATE TOTAL_AMT_DW.dbo.TOTAL_AMOUNT_FACT1
SET STS_AMOUNT=0
WHERE STS='Paid'
UPDATE TOTAL_AMT_DW.dbo.TOTAL_AMOUNT_FACT1
SET STS_AMOUNT= AMOUNT_TOTAL
WHERE STS='Outstanding'
UPDATE TOTAL_AMT_DW.dbo.TOTAL_AMOUNT_FACT1
SET STS_AMOUNT= AMOUNT_TOTAL
WHERE STS='Escheat'
